//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekres.QuickSurrender.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekres.QuickSurrender.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Command.
        /// </summary>
        internal static string Chat_Command {
            get {
                return ResourceManager.GetString("Chat Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Display.
        /// </summary>
        internal static string Chat_Display {
            get {
                return ResourceManager.GetString("Chat Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Message.
        /// </summary>
        internal static string Chat_Message {
            get {
                return ResourceManager.GetString("Chat Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command recharging..
        /// </summary>
        internal static string Command_recharging_ {
            get {
                return ResourceManager.GetString("Command recharging.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concede defeat..
        /// </summary>
        internal static string Concede_defeat_ {
            get {
                return ResourceManager.GetString("Concede defeat.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concede defeat by finishing yourself..
        /// </summary>
        internal static string Concede_defeat_by_finishing_yourself_ {
            get {
                return ResourceManager.GetString("Concede defeat by finishing yourself.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Options.
        /// </summary>
        internal static string Control_Options {
            get {
                return ResourceManager.GetString("Control Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeated.
        /// </summary>
        internal static string Defeated {
            get {
                return ResourceManager.GetString("Defeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines how the surrender skill is displayed in chat using [Ctrl] or [Shift] + [Left Mouse]..
        /// </summary>
        internal static string Determines_how_the_surrender_skill_is_displayed_in_chat_using__Ctrl__or__Shift_____Left_Mouse__ {
            get {
                return ResourceManager.GetString("Determines how the surrender skill is displayed in chat using [Ctrl] or [Shift] +" +
                        " [Left Mouse].", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a skill to assist in conceding defeat..
        /// </summary>
        internal static string Displays_a_skill_to_assist_in_conceding_defeat_ {
            get {
                return ResourceManager.GetString("Displays a skill to assist in conceding defeat.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give focus to the chat edit box..
        /// </summary>
        internal static string Give_focus_to_the_chat_edit_box_ {
            get {
                return ResourceManager.GetString("Give focus to the chat edit box.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        internal static string Hotkeys {
            get {
                return ResourceManager.GetString("Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Surrender Skill.
        /// </summary>
        internal static string Show_Surrender_Skill {
            get {
                return ResourceManager.GetString("Show Surrender Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        internal static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill recharging..
        /// </summary>
        internal static string Skill_recharging_ {
            get {
                return ResourceManager.GetString("Skill recharging.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrender.
        /// </summary>
        internal static string Surrender {
            get {
                return ResourceManager.GetString("Surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface.
        /// </summary>
        internal static string User_Interface {
            get {
                return ResourceManager.GetString("User Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are defeated..
        /// </summary>
        internal static string You_are_defeated_ {
            get {
                return ResourceManager.GetString("You are defeated.", resourceCulture);
            }
        }
    }
}
